name: Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [opened, synchronize]

jobs:
  pipeline_jobs:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel previous Redudant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - name: get last commit → DEV
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up node → DEV
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: run npm ci → DEV
        run: npm ci
      - name: run npm test → DEV_
        run: npm test
