name: Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: get last commit → DEV_BUILD
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up node → DEV_BUILD
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: run npm ci → DEV_BUILD
        run: npm ci
      - name: build
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next/

  test:
    runs-on: ubuntu-22.04
    steps:
      - name: get last commit → DEV_TEST
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up node → DEV_TEST
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: run npm ci → DEV_TEST
        run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: nextjs-build
          path: .next/
      - name: run npm test → DEV_999
        run: npm test
