name: Pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  npm_cache:
    runs-on: ubuntu-22.04
    steps:
      - name: get last commit → DEV_NPM_CACHE
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up node → DEV_NPM_CACHE
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: run npm ci → DEV_NPM_CACHE_
        run: npm ci
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

  build:
    needs: [npm_cache]
    runs-on: ubuntu-22.04
    steps:
      - name: get last commit → DEV_NPM_CACHE
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up node → DEV_NPM_CACHE
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: build
        run: npm run build

  test:
    needs: [npm_cache]
    runs-on: ubuntu-22.04
    steps:
      - name: get last commit → DEV_NPM_CACHE
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up node → DEV_NPM_CACHE
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: run npm test → DEV_999
        run: npm test
